### ISSUE TITLE
ユーザ認証機能

### ISSUE THREAD

**Issue by nanairo3** [nanairo3/Cinema_Log#1]
1. ユーザ認証機能
- [x] user table定義
- [x] devise gem 導入（model, controller, view(erb)  作成）
- [x] devise、validateエラーメッセージ日本語化
2. レイアウト修正
3. Rspecによるmodel system テスト
- [x] model
- [x] system

**Comment by toyokappa** [comment]
erbは冗長で読みづらいのでslimでいいと思います。

**Comment by nanairo3** [comment]
slimで作成します！

**Comment by toyokappa** [comment]
このIssueの粒度が大きそうな気がしていて、railsの初期設定（generatorの設定、rspecの設定など）とlayout作成で1つ、ユーザー認証系の実装で1つというようにしたほうがよいかなぁと思いました。（粒度が小さいほどレビューはしやすいので）

参考までRailsの初期設定はこんな感じのができてるといいかなぁと思います。

```
# Railsの初期設定やっておいたほうがいいこと
- generatorの設定
- Timezoneの設定
- デバッグ、コンソールをpryに変更
- rspecの設定
- rubocopの設定
```

**Comment by nanairo3** [comment]
承知いたしました！
1. railsの初期設定
2. layout作成
3.  ユーザー認証系の実装

の順で行っていきます！
