### ISSUE TITLE
プロフィール画像アップロード、表示

### ISSUE THREAD

**Issue by nanairo3** [nanairo3/Cinema_Log#2]
1. S3バケット作成(IAMユーザ作成済み)
2. ActiveStorage設定
3. Userにアタッチ
- [ ] model設定(validates)
- [ ] User.new デフォルト画像設定
- [x] User.edit アップロードできるようにする
- [x] User show index（ユーザ一覧） _header（ヘッダー部分）　修正
4. Rspec test
- [ ] model
- [x] system

**Comment by toyokappa** [comment]
`index_header`って何のことでしたっけ？

**Comment by nanairo3** [comment]
index：ユーザ一覧
_header:全viewに共通するヘッダー部分
のことを意図して書きました。

**Comment by toyokappa** [comment]
layoutsの話ですね。理解です。
