### ISSUE TITLE
映画情報取得

### ISSUE THREAD

**Issue by nanairo3** [nanairo3/Cinema_Log#3]
1. テーブル定義（TMDbドキュメント参照）
- movie テーブル
- genre テーブル
- movie_genreテーブル
2. 外部API実装
- [x] lib?model?controller?（どこに書けばいいか迷ってます） 情報取得部作成
- [x] 必要であれば通信用のgemを入手
- [x]  DB保存
3. 映画情報をviewに表示
- [x] root_path
- [x] ページネイション（gem kaminari）
4. Rspec Test
- [ ] 通信テスト
- [ ] system テスト

**Comment by toyokappa** [comment]
API自体の処理は`app/services`というディレクトリを作成して、そちらにPOROで通信処理を書いて、実際のバッチを走らせるための処理については`app/batch`というディレクトリを作成して、そちらに`cron`か何かで`rails runner`を立たけるように実装するのがいいかなぁと思いました。

**Comment by toyokappa** [comment]
問題なく取得できるかのテストも書いたほうがいいですね。

**Comment by nanairo3** [comment]
API実装について何となく方針が見えました！ありがとうございます。
テストについて承知いたしました。
